export {default as About} from "./about/About";
export {default as AddCommiittees} from "./addCommittees/AddCommiittees";
export {default as AllCommittees} from "./allCommittees/AllCommittees";
export {default as Committees} from "./committees/Committees";
export {default as Dashboard} from "./dashboard/Dashboard";
export {default as Home} from "./home/Home";
export {default as Layout} from "./layout/Layout";
export {default as Login} from "./login/Login";
export {default as ViewCommittee} from "./viewCommittee/ViewCommittee";